// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofiles/FlowMessage.proto

package rina.encoding.impl.googleprotobuf.flow;

public final class FlowMessage {
  private FlowMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class connectionId_t extends
      com.google.protobuf.GeneratedMessage {
    // Use connectionId_t.newBuilder() to construct.
    private connectionId_t() {
      initFields();
    }
    private connectionId_t(boolean noInit) {}
    
    private static final connectionId_t defaultInstance;
    public static connectionId_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public connectionId_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.encoding.impl.googleprotobuf.flow.FlowMessage.internal_static_rina_messages_connectionId_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.encoding.impl.googleprotobuf.flow.FlowMessage.internal_static_rina_messages_connectionId_t_fieldAccessorTable;
    }
    
    // optional uint64 qosId = 1;
    public static final int QOSID_FIELD_NUMBER = 1;
    private boolean hasQosId;
    private long qosId_ = 0L;
    public boolean hasQosId() { return hasQosId; }
    public long getQosId() { return qosId_; }
    
    // optional uint64 sourceCEPId = 2;
    public static final int SOURCECEPID_FIELD_NUMBER = 2;
    private boolean hasSourceCEPId;
    private long sourceCEPId_ = 0L;
    public boolean hasSourceCEPId() { return hasSourceCEPId; }
    public long getSourceCEPId() { return sourceCEPId_; }
    
    // optional uint64 destinationCEPId = 3;
    public static final int DESTINATIONCEPID_FIELD_NUMBER = 3;
    private boolean hasDestinationCEPId;
    private long destinationCEPId_ = 0L;
    public boolean hasDestinationCEPId() { return hasDestinationCEPId; }
    public long getDestinationCEPId() { return destinationCEPId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasQosId()) {
        output.writeUInt64(1, getQosId());
      }
      if (hasSourceCEPId()) {
        output.writeUInt64(2, getSourceCEPId());
      }
      if (hasDestinationCEPId()) {
        output.writeUInt64(3, getDestinationCEPId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasQosId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, getQosId());
      }
      if (hasSourceCEPId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, getSourceCEPId());
      }
      if (hasDestinationCEPId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, getDestinationCEPId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t result;
      
      // Construct using rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t();
        return builder;
      }
      
      protected rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t.getDescriptor();
      }
      
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t getDefaultInstanceForType() {
        return rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t) {
          return mergeFrom((rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t other) {
        if (other == rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t.getDefaultInstance()) return this;
        if (other.hasQosId()) {
          setQosId(other.getQosId());
        }
        if (other.hasSourceCEPId()) {
          setSourceCEPId(other.getSourceCEPId());
        }
        if (other.hasDestinationCEPId()) {
          setDestinationCEPId(other.getDestinationCEPId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setQosId(input.readUInt64());
              break;
            }
            case 16: {
              setSourceCEPId(input.readUInt64());
              break;
            }
            case 24: {
              setDestinationCEPId(input.readUInt64());
              break;
            }
          }
        }
      }
      
      
      // optional uint64 qosId = 1;
      public boolean hasQosId() {
        return result.hasQosId();
      }
      public long getQosId() {
        return result.getQosId();
      }
      public Builder setQosId(long value) {
        result.hasQosId = true;
        result.qosId_ = value;
        return this;
      }
      public Builder clearQosId() {
        result.hasQosId = false;
        result.qosId_ = 0L;
        return this;
      }
      
      // optional uint64 sourceCEPId = 2;
      public boolean hasSourceCEPId() {
        return result.hasSourceCEPId();
      }
      public long getSourceCEPId() {
        return result.getSourceCEPId();
      }
      public Builder setSourceCEPId(long value) {
        result.hasSourceCEPId = true;
        result.sourceCEPId_ = value;
        return this;
      }
      public Builder clearSourceCEPId() {
        result.hasSourceCEPId = false;
        result.sourceCEPId_ = 0L;
        return this;
      }
      
      // optional uint64 destinationCEPId = 3;
      public boolean hasDestinationCEPId() {
        return result.hasDestinationCEPId();
      }
      public long getDestinationCEPId() {
        return result.getDestinationCEPId();
      }
      public Builder setDestinationCEPId(long value) {
        result.hasDestinationCEPId = true;
        result.destinationCEPId_ = value;
        return this;
      }
      public Builder clearDestinationCEPId() {
        result.hasDestinationCEPId = false;
        result.destinationCEPId_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.connectionId_t)
    }
    
    static {
      defaultInstance = new connectionId_t(true);
      rina.encoding.impl.googleprotobuf.flow.FlowMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.connectionId_t)
  }
  
  public static final class qosParameter_t extends
      com.google.protobuf.GeneratedMessage {
    // Use qosParameter_t.newBuilder() to construct.
    private qosParameter_t() {
      initFields();
    }
    private qosParameter_t(boolean noInit) {}
    
    private static final qosParameter_t defaultInstance;
    public static qosParameter_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public qosParameter_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.encoding.impl.googleprotobuf.flow.FlowMessage.internal_static_rina_messages_qosParameter_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.encoding.impl.googleprotobuf.flow.FlowMessage.internal_static_rina_messages_qosParameter_t_fieldAccessorTable;
    }
    
    // required string parameterName = 1;
    public static final int PARAMETERNAME_FIELD_NUMBER = 1;
    private boolean hasParameterName;
    private java.lang.String parameterName_ = "";
    public boolean hasParameterName() { return hasParameterName; }
    public java.lang.String getParameterName() { return parameterName_; }
    
    // required string parameterValue = 2;
    public static final int PARAMETERVALUE_FIELD_NUMBER = 2;
    private boolean hasParameterValue;
    private java.lang.String parameterValue_ = "";
    public boolean hasParameterValue() { return hasParameterValue; }
    public java.lang.String getParameterValue() { return parameterValue_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      if (!hasParameterName) return false;
      if (!hasParameterValue) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasParameterName()) {
        output.writeString(1, getParameterName());
      }
      if (hasParameterValue()) {
        output.writeString(2, getParameterValue());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasParameterName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getParameterName());
      }
      if (hasParameterValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getParameterValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t result;
      
      // Construct using rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t();
        return builder;
      }
      
      protected rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t.getDescriptor();
      }
      
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t getDefaultInstanceForType() {
        return rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t) {
          return mergeFrom((rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t other) {
        if (other == rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t.getDefaultInstance()) return this;
        if (other.hasParameterName()) {
          setParameterName(other.getParameterName());
        }
        if (other.hasParameterValue()) {
          setParameterValue(other.getParameterValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setParameterName(input.readString());
              break;
            }
            case 18: {
              setParameterValue(input.readString());
              break;
            }
          }
        }
      }
      
      
      // required string parameterName = 1;
      public boolean hasParameterName() {
        return result.hasParameterName();
      }
      public java.lang.String getParameterName() {
        return result.getParameterName();
      }
      public Builder setParameterName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasParameterName = true;
        result.parameterName_ = value;
        return this;
      }
      public Builder clearParameterName() {
        result.hasParameterName = false;
        result.parameterName_ = getDefaultInstance().getParameterName();
        return this;
      }
      
      // required string parameterValue = 2;
      public boolean hasParameterValue() {
        return result.hasParameterValue();
      }
      public java.lang.String getParameterValue() {
        return result.getParameterValue();
      }
      public Builder setParameterValue(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasParameterValue = true;
        result.parameterValue_ = value;
        return this;
      }
      public Builder clearParameterValue() {
        result.hasParameterValue = false;
        result.parameterValue_ = getDefaultInstance().getParameterValue();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.qosParameter_t)
    }
    
    static {
      defaultInstance = new qosParameter_t(true);
      rina.encoding.impl.googleprotobuf.flow.FlowMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.qosParameter_t)
  }
  
  public static final class Flow extends
      com.google.protobuf.GeneratedMessage {
    // Use Flow.newBuilder() to construct.
    private Flow() {
      initFields();
    }
    private Flow(boolean noInit) {}
    
    private static final Flow defaultInstance;
    public static Flow getDefaultInstance() {
      return defaultInstance;
    }
    
    public Flow getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.encoding.impl.googleprotobuf.flow.FlowMessage.internal_static_rina_messages_Flow_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.encoding.impl.googleprotobuf.flow.FlowMessage.internal_static_rina_messages_Flow_fieldAccessorTable;
    }
    
    // required .rina.messages.applicationProcessNamingInfo_t sourceNamingInfo = 1;
    public static final int SOURCENAMINGINFO_FIELD_NUMBER = 1;
    private boolean hasSourceNamingInfo;
    private rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t sourceNamingInfo_;
    public boolean hasSourceNamingInfo() { return hasSourceNamingInfo; }
    public rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t getSourceNamingInfo() { return sourceNamingInfo_; }
    
    // required .rina.messages.applicationProcessNamingInfo_t destinationNamingInfo = 2;
    public static final int DESTINATIONNAMINGINFO_FIELD_NUMBER = 2;
    private boolean hasDestinationNamingInfo;
    private rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t destinationNamingInfo_;
    public boolean hasDestinationNamingInfo() { return hasDestinationNamingInfo; }
    public rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t getDestinationNamingInfo() { return destinationNamingInfo_; }
    
    // optional uint64 sourcePortId = 3;
    public static final int SOURCEPORTID_FIELD_NUMBER = 3;
    private boolean hasSourcePortId;
    private long sourcePortId_ = 0L;
    public boolean hasSourcePortId() { return hasSourcePortId; }
    public long getSourcePortId() { return sourcePortId_; }
    
    // optional uint64 destinationPortId = 4;
    public static final int DESTINATIONPORTID_FIELD_NUMBER = 4;
    private boolean hasDestinationPortId;
    private long destinationPortId_ = 0L;
    public boolean hasDestinationPortId() { return hasDestinationPortId; }
    public long getDestinationPortId() { return destinationPortId_; }
    
    // optional uint64 sourceAddress = 5;
    public static final int SOURCEADDRESS_FIELD_NUMBER = 5;
    private boolean hasSourceAddress;
    private long sourceAddress_ = 0L;
    public boolean hasSourceAddress() { return hasSourceAddress; }
    public long getSourceAddress() { return sourceAddress_; }
    
    // optional uint64 destinationAddress = 6;
    public static final int DESTINATIONADDRESS_FIELD_NUMBER = 6;
    private boolean hasDestinationAddress;
    private long destinationAddress_ = 0L;
    public boolean hasDestinationAddress() { return hasDestinationAddress; }
    public long getDestinationAddress() { return destinationAddress_; }
    
    // repeated .rina.messages.connectionId_t connectionIds = 7;
    public static final int CONNECTIONIDS_FIELD_NUMBER = 7;
    private java.util.List<rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t> connectionIds_ =
      java.util.Collections.emptyList();
    public java.util.List<rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t> getConnectionIdsList() {
      return connectionIds_;
    }
    public int getConnectionIdsCount() { return connectionIds_.size(); }
    public rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t getConnectionIds(int index) {
      return connectionIds_.get(index);
    }
    
    // optional uint32 currentConnectionId = 8;
    public static final int CURRENTCONNECTIONID_FIELD_NUMBER = 8;
    private boolean hasCurrentConnectionId;
    private int currentConnectionId_ = 0;
    public boolean hasCurrentConnectionId() { return hasCurrentConnectionId; }
    public int getCurrentConnectionId() { return currentConnectionId_; }
    
    // optional bytes state = 9;
    public static final int STATE_FIELD_NUMBER = 9;
    private boolean hasState;
    private com.google.protobuf.ByteString state_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasState() { return hasState; }
    public com.google.protobuf.ByteString getState() { return state_; }
    
    // repeated .rina.messages.qosParameter_t qosParameters = 10;
    public static final int QOSPARAMETERS_FIELD_NUMBER = 10;
    private java.util.List<rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t> qosParameters_ =
      java.util.Collections.emptyList();
    public java.util.List<rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t> getQosParametersList() {
      return qosParameters_;
    }
    public int getQosParametersCount() { return qosParameters_.size(); }
    public rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t getQosParameters(int index) {
      return qosParameters_.get(index);
    }
    
    // repeated string policies = 11;
    public static final int POLICIES_FIELD_NUMBER = 11;
    private java.util.List<java.lang.String> policies_ =
      java.util.Collections.emptyList();
    public java.util.List<java.lang.String> getPoliciesList() {
      return policies_;
    }
    public int getPoliciesCount() { return policies_.size(); }
    public java.lang.String getPolicies(int index) {
      return policies_.get(index);
    }
    
    // optional bytes accessControl = 12;
    public static final int ACCESSCONTROL_FIELD_NUMBER = 12;
    private boolean hasAccessControl;
    private com.google.protobuf.ByteString accessControl_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasAccessControl() { return hasAccessControl; }
    public com.google.protobuf.ByteString getAccessControl() { return accessControl_; }
    
    // optional uint32 maxCreateFlowRetries = 13;
    public static final int MAXCREATEFLOWRETRIES_FIELD_NUMBER = 13;
    private boolean hasMaxCreateFlowRetries;
    private int maxCreateFlowRetries_ = 0;
    public boolean hasMaxCreateFlowRetries() { return hasMaxCreateFlowRetries; }
    public int getMaxCreateFlowRetries() { return maxCreateFlowRetries_; }
    
    // optional uint32 createFlowRetries = 14;
    public static final int CREATEFLOWRETRIES_FIELD_NUMBER = 14;
    private boolean hasCreateFlowRetries;
    private int createFlowRetries_ = 0;
    public boolean hasCreateFlowRetries() { return hasCreateFlowRetries; }
    public int getCreateFlowRetries() { return createFlowRetries_; }
    
    // optional uint32 hopCount = 15;
    public static final int HOPCOUNT_FIELD_NUMBER = 15;
    private boolean hasHopCount;
    private int hopCount_ = 0;
    public boolean hasHopCount() { return hasHopCount; }
    public int getHopCount() { return hopCount_; }
    
    private void initFields() {
      sourceNamingInfo_ = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance();
      destinationNamingInfo_ = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasSourceNamingInfo) return false;
      if (!hasDestinationNamingInfo) return false;
      if (!getSourceNamingInfo().isInitialized()) return false;
      if (!getDestinationNamingInfo().isInitialized()) return false;
      for (rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t element : getQosParametersList()) {
        if (!element.isInitialized()) return false;
      }
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSourceNamingInfo()) {
        output.writeMessage(1, getSourceNamingInfo());
      }
      if (hasDestinationNamingInfo()) {
        output.writeMessage(2, getDestinationNamingInfo());
      }
      if (hasSourcePortId()) {
        output.writeUInt64(3, getSourcePortId());
      }
      if (hasDestinationPortId()) {
        output.writeUInt64(4, getDestinationPortId());
      }
      if (hasSourceAddress()) {
        output.writeUInt64(5, getSourceAddress());
      }
      if (hasDestinationAddress()) {
        output.writeUInt64(6, getDestinationAddress());
      }
      for (rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t element : getConnectionIdsList()) {
        output.writeMessage(7, element);
      }
      if (hasCurrentConnectionId()) {
        output.writeUInt32(8, getCurrentConnectionId());
      }
      if (hasState()) {
        output.writeBytes(9, getState());
      }
      for (rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t element : getQosParametersList()) {
        output.writeMessage(10, element);
      }
      for (java.lang.String element : getPoliciesList()) {
        output.writeString(11, element);
      }
      if (hasAccessControl()) {
        output.writeBytes(12, getAccessControl());
      }
      if (hasMaxCreateFlowRetries()) {
        output.writeUInt32(13, getMaxCreateFlowRetries());
      }
      if (hasCreateFlowRetries()) {
        output.writeUInt32(14, getCreateFlowRetries());
      }
      if (hasHopCount()) {
        output.writeUInt32(15, getHopCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSourceNamingInfo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSourceNamingInfo());
      }
      if (hasDestinationNamingInfo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDestinationNamingInfo());
      }
      if (hasSourcePortId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, getSourcePortId());
      }
      if (hasDestinationPortId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, getDestinationPortId());
      }
      if (hasSourceAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, getSourceAddress());
      }
      if (hasDestinationAddress()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, getDestinationAddress());
      }
      for (rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t element : getConnectionIdsList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, element);
      }
      if (hasCurrentConnectionId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, getCurrentConnectionId());
      }
      if (hasState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, getState());
      }
      for (rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t element : getQosParametersList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, element);
      }
      {
        int dataSize = 0;
        for (java.lang.String element : getPoliciesList()) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeStringSizeNoTag(element);
        }
        size += dataSize;
        size += 1 * getPoliciesList().size();
      }
      if (hasAccessControl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(12, getAccessControl());
      }
      if (hasMaxCreateFlowRetries()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, getMaxCreateFlowRetries());
      }
      if (hasCreateFlowRetries()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(14, getCreateFlowRetries());
      }
      if (hasHopCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(15, getHopCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow result;
      
      // Construct using rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow();
        return builder;
      }
      
      protected rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow.getDescriptor();
      }
      
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow getDefaultInstanceForType() {
        return rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.connectionIds_ != java.util.Collections.EMPTY_LIST) {
          result.connectionIds_ =
            java.util.Collections.unmodifiableList(result.connectionIds_);
        }
        if (result.qosParameters_ != java.util.Collections.EMPTY_LIST) {
          result.qosParameters_ =
            java.util.Collections.unmodifiableList(result.qosParameters_);
        }
        if (result.policies_ != java.util.Collections.EMPTY_LIST) {
          result.policies_ =
            java.util.Collections.unmodifiableList(result.policies_);
        }
        rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow) {
          return mergeFrom((rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow other) {
        if (other == rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow.getDefaultInstance()) return this;
        if (other.hasSourceNamingInfo()) {
          mergeSourceNamingInfo(other.getSourceNamingInfo());
        }
        if (other.hasDestinationNamingInfo()) {
          mergeDestinationNamingInfo(other.getDestinationNamingInfo());
        }
        if (other.hasSourcePortId()) {
          setSourcePortId(other.getSourcePortId());
        }
        if (other.hasDestinationPortId()) {
          setDestinationPortId(other.getDestinationPortId());
        }
        if (other.hasSourceAddress()) {
          setSourceAddress(other.getSourceAddress());
        }
        if (other.hasDestinationAddress()) {
          setDestinationAddress(other.getDestinationAddress());
        }
        if (!other.connectionIds_.isEmpty()) {
          if (result.connectionIds_.isEmpty()) {
            result.connectionIds_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t>();
          }
          result.connectionIds_.addAll(other.connectionIds_);
        }
        if (other.hasCurrentConnectionId()) {
          setCurrentConnectionId(other.getCurrentConnectionId());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (!other.qosParameters_.isEmpty()) {
          if (result.qosParameters_.isEmpty()) {
            result.qosParameters_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t>();
          }
          result.qosParameters_.addAll(other.qosParameters_);
        }
        if (!other.policies_.isEmpty()) {
          if (result.policies_.isEmpty()) {
            result.policies_ = new java.util.ArrayList<java.lang.String>();
          }
          result.policies_.addAll(other.policies_);
        }
        if (other.hasAccessControl()) {
          setAccessControl(other.getAccessControl());
        }
        if (other.hasMaxCreateFlowRetries()) {
          setMaxCreateFlowRetries(other.getMaxCreateFlowRetries());
        }
        if (other.hasCreateFlowRetries()) {
          setCreateFlowRetries(other.getCreateFlowRetries());
        }
        if (other.hasHopCount()) {
          setHopCount(other.getHopCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.Builder subBuilder = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.newBuilder();
              if (hasSourceNamingInfo()) {
                subBuilder.mergeFrom(getSourceNamingInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSourceNamingInfo(subBuilder.buildPartial());
              break;
            }
            case 18: {
              rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.Builder subBuilder = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.newBuilder();
              if (hasDestinationNamingInfo()) {
                subBuilder.mergeFrom(getDestinationNamingInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDestinationNamingInfo(subBuilder.buildPartial());
              break;
            }
            case 24: {
              setSourcePortId(input.readUInt64());
              break;
            }
            case 32: {
              setDestinationPortId(input.readUInt64());
              break;
            }
            case 40: {
              setSourceAddress(input.readUInt64());
              break;
            }
            case 48: {
              setDestinationAddress(input.readUInt64());
              break;
            }
            case 58: {
              rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t.Builder subBuilder = rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addConnectionIds(subBuilder.buildPartial());
              break;
            }
            case 64: {
              setCurrentConnectionId(input.readUInt32());
              break;
            }
            case 74: {
              setState(input.readBytes());
              break;
            }
            case 82: {
              rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t.Builder subBuilder = rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addQosParameters(subBuilder.buildPartial());
              break;
            }
            case 90: {
              addPolicies(input.readString());
              break;
            }
            case 98: {
              setAccessControl(input.readBytes());
              break;
            }
            case 104: {
              setMaxCreateFlowRetries(input.readUInt32());
              break;
            }
            case 112: {
              setCreateFlowRetries(input.readUInt32());
              break;
            }
            case 120: {
              setHopCount(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // required .rina.messages.applicationProcessNamingInfo_t sourceNamingInfo = 1;
      public boolean hasSourceNamingInfo() {
        return result.hasSourceNamingInfo();
      }
      public rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t getSourceNamingInfo() {
        return result.getSourceNamingInfo();
      }
      public Builder setSourceNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSourceNamingInfo = true;
        result.sourceNamingInfo_ = value;
        return this;
      }
      public Builder setSourceNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.Builder builderForValue) {
        result.hasSourceNamingInfo = true;
        result.sourceNamingInfo_ = builderForValue.build();
        return this;
      }
      public Builder mergeSourceNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t value) {
        if (result.hasSourceNamingInfo() &&
            result.sourceNamingInfo_ != rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance()) {
          result.sourceNamingInfo_ =
            rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.newBuilder(result.sourceNamingInfo_).mergeFrom(value).buildPartial();
        } else {
          result.sourceNamingInfo_ = value;
        }
        result.hasSourceNamingInfo = true;
        return this;
      }
      public Builder clearSourceNamingInfo() {
        result.hasSourceNamingInfo = false;
        result.sourceNamingInfo_ = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance();
        return this;
      }
      
      // required .rina.messages.applicationProcessNamingInfo_t destinationNamingInfo = 2;
      public boolean hasDestinationNamingInfo() {
        return result.hasDestinationNamingInfo();
      }
      public rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t getDestinationNamingInfo() {
        return result.getDestinationNamingInfo();
      }
      public Builder setDestinationNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDestinationNamingInfo = true;
        result.destinationNamingInfo_ = value;
        return this;
      }
      public Builder setDestinationNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.Builder builderForValue) {
        result.hasDestinationNamingInfo = true;
        result.destinationNamingInfo_ = builderForValue.build();
        return this;
      }
      public Builder mergeDestinationNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t value) {
        if (result.hasDestinationNamingInfo() &&
            result.destinationNamingInfo_ != rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance()) {
          result.destinationNamingInfo_ =
            rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.newBuilder(result.destinationNamingInfo_).mergeFrom(value).buildPartial();
        } else {
          result.destinationNamingInfo_ = value;
        }
        result.hasDestinationNamingInfo = true;
        return this;
      }
      public Builder clearDestinationNamingInfo() {
        result.hasDestinationNamingInfo = false;
        result.destinationNamingInfo_ = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance();
        return this;
      }
      
      // optional uint64 sourcePortId = 3;
      public boolean hasSourcePortId() {
        return result.hasSourcePortId();
      }
      public long getSourcePortId() {
        return result.getSourcePortId();
      }
      public Builder setSourcePortId(long value) {
        result.hasSourcePortId = true;
        result.sourcePortId_ = value;
        return this;
      }
      public Builder clearSourcePortId() {
        result.hasSourcePortId = false;
        result.sourcePortId_ = 0L;
        return this;
      }
      
      // optional uint64 destinationPortId = 4;
      public boolean hasDestinationPortId() {
        return result.hasDestinationPortId();
      }
      public long getDestinationPortId() {
        return result.getDestinationPortId();
      }
      public Builder setDestinationPortId(long value) {
        result.hasDestinationPortId = true;
        result.destinationPortId_ = value;
        return this;
      }
      public Builder clearDestinationPortId() {
        result.hasDestinationPortId = false;
        result.destinationPortId_ = 0L;
        return this;
      }
      
      // optional uint64 sourceAddress = 5;
      public boolean hasSourceAddress() {
        return result.hasSourceAddress();
      }
      public long getSourceAddress() {
        return result.getSourceAddress();
      }
      public Builder setSourceAddress(long value) {
        result.hasSourceAddress = true;
        result.sourceAddress_ = value;
        return this;
      }
      public Builder clearSourceAddress() {
        result.hasSourceAddress = false;
        result.sourceAddress_ = 0L;
        return this;
      }
      
      // optional uint64 destinationAddress = 6;
      public boolean hasDestinationAddress() {
        return result.hasDestinationAddress();
      }
      public long getDestinationAddress() {
        return result.getDestinationAddress();
      }
      public Builder setDestinationAddress(long value) {
        result.hasDestinationAddress = true;
        result.destinationAddress_ = value;
        return this;
      }
      public Builder clearDestinationAddress() {
        result.hasDestinationAddress = false;
        result.destinationAddress_ = 0L;
        return this;
      }
      
      // repeated .rina.messages.connectionId_t connectionIds = 7;
      public java.util.List<rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t> getConnectionIdsList() {
        return java.util.Collections.unmodifiableList(result.connectionIds_);
      }
      public int getConnectionIdsCount() {
        return result.getConnectionIdsCount();
      }
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t getConnectionIds(int index) {
        return result.getConnectionIds(index);
      }
      public Builder setConnectionIds(int index, rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.connectionIds_.set(index, value);
        return this;
      }
      public Builder setConnectionIds(int index, rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t.Builder builderForValue) {
        result.connectionIds_.set(index, builderForValue.build());
        return this;
      }
      public Builder addConnectionIds(rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.connectionIds_.isEmpty()) {
          result.connectionIds_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t>();
        }
        result.connectionIds_.add(value);
        return this;
      }
      public Builder addConnectionIds(rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t.Builder builderForValue) {
        if (result.connectionIds_.isEmpty()) {
          result.connectionIds_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t>();
        }
        result.connectionIds_.add(builderForValue.build());
        return this;
      }
      public Builder addAllConnectionIds(
          java.lang.Iterable<? extends rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t> values) {
        if (result.connectionIds_.isEmpty()) {
          result.connectionIds_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t>();
        }
        super.addAll(values, result.connectionIds_);
        return this;
      }
      public Builder clearConnectionIds() {
        result.connectionIds_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional uint32 currentConnectionId = 8;
      public boolean hasCurrentConnectionId() {
        return result.hasCurrentConnectionId();
      }
      public int getCurrentConnectionId() {
        return result.getCurrentConnectionId();
      }
      public Builder setCurrentConnectionId(int value) {
        result.hasCurrentConnectionId = true;
        result.currentConnectionId_ = value;
        return this;
      }
      public Builder clearCurrentConnectionId() {
        result.hasCurrentConnectionId = false;
        result.currentConnectionId_ = 0;
        return this;
      }
      
      // optional bytes state = 9;
      public boolean hasState() {
        return result.hasState();
      }
      public com.google.protobuf.ByteString getState() {
        return result.getState();
      }
      public Builder setState(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = getDefaultInstance().getState();
        return this;
      }
      
      // repeated .rina.messages.qosParameter_t qosParameters = 10;
      public java.util.List<rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t> getQosParametersList() {
        return java.util.Collections.unmodifiableList(result.qosParameters_);
      }
      public int getQosParametersCount() {
        return result.getQosParametersCount();
      }
      public rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t getQosParameters(int index) {
        return result.getQosParameters(index);
      }
      public Builder setQosParameters(int index, rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.qosParameters_.set(index, value);
        return this;
      }
      public Builder setQosParameters(int index, rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t.Builder builderForValue) {
        result.qosParameters_.set(index, builderForValue.build());
        return this;
      }
      public Builder addQosParameters(rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.qosParameters_.isEmpty()) {
          result.qosParameters_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t>();
        }
        result.qosParameters_.add(value);
        return this;
      }
      public Builder addQosParameters(rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t.Builder builderForValue) {
        if (result.qosParameters_.isEmpty()) {
          result.qosParameters_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t>();
        }
        result.qosParameters_.add(builderForValue.build());
        return this;
      }
      public Builder addAllQosParameters(
          java.lang.Iterable<? extends rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t> values) {
        if (result.qosParameters_.isEmpty()) {
          result.qosParameters_ = new java.util.ArrayList<rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t>();
        }
        super.addAll(values, result.qosParameters_);
        return this;
      }
      public Builder clearQosParameters() {
        result.qosParameters_ = java.util.Collections.emptyList();
        return this;
      }
      
      // repeated string policies = 11;
      public java.util.List<java.lang.String> getPoliciesList() {
        return java.util.Collections.unmodifiableList(result.policies_);
      }
      public int getPoliciesCount() {
        return result.getPoliciesCount();
      }
      public java.lang.String getPolicies(int index) {
        return result.getPolicies(index);
      }
      public Builder setPolicies(int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.policies_.set(index, value);
        return this;
      }
      public Builder addPolicies(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  if (result.policies_.isEmpty()) {
          result.policies_ = new java.util.ArrayList<java.lang.String>();
        }
        result.policies_.add(value);
        return this;
      }
      public Builder addAllPolicies(
          java.lang.Iterable<? extends java.lang.String> values) {
        if (result.policies_.isEmpty()) {
          result.policies_ = new java.util.ArrayList<java.lang.String>();
        }
        super.addAll(values, result.policies_);
        return this;
      }
      public Builder clearPolicies() {
        result.policies_ = java.util.Collections.emptyList();
        return this;
      }
      
      // optional bytes accessControl = 12;
      public boolean hasAccessControl() {
        return result.hasAccessControl();
      }
      public com.google.protobuf.ByteString getAccessControl() {
        return result.getAccessControl();
      }
      public Builder setAccessControl(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAccessControl = true;
        result.accessControl_ = value;
        return this;
      }
      public Builder clearAccessControl() {
        result.hasAccessControl = false;
        result.accessControl_ = getDefaultInstance().getAccessControl();
        return this;
      }
      
      // optional uint32 maxCreateFlowRetries = 13;
      public boolean hasMaxCreateFlowRetries() {
        return result.hasMaxCreateFlowRetries();
      }
      public int getMaxCreateFlowRetries() {
        return result.getMaxCreateFlowRetries();
      }
      public Builder setMaxCreateFlowRetries(int value) {
        result.hasMaxCreateFlowRetries = true;
        result.maxCreateFlowRetries_ = value;
        return this;
      }
      public Builder clearMaxCreateFlowRetries() {
        result.hasMaxCreateFlowRetries = false;
        result.maxCreateFlowRetries_ = 0;
        return this;
      }
      
      // optional uint32 createFlowRetries = 14;
      public boolean hasCreateFlowRetries() {
        return result.hasCreateFlowRetries();
      }
      public int getCreateFlowRetries() {
        return result.getCreateFlowRetries();
      }
      public Builder setCreateFlowRetries(int value) {
        result.hasCreateFlowRetries = true;
        result.createFlowRetries_ = value;
        return this;
      }
      public Builder clearCreateFlowRetries() {
        result.hasCreateFlowRetries = false;
        result.createFlowRetries_ = 0;
        return this;
      }
      
      // optional uint32 hopCount = 15;
      public boolean hasHopCount() {
        return result.hasHopCount();
      }
      public int getHopCount() {
        return result.getHopCount();
      }
      public Builder setHopCount(int value) {
        result.hasHopCount = true;
        result.hopCount_ = value;
        return this;
      }
      public Builder clearHopCount() {
        result.hasHopCount = false;
        result.hopCount_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.Flow)
    }
    
    static {
      defaultInstance = new Flow(true);
      rina.encoding.impl.googleprotobuf.flow.FlowMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.Flow)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_connectionId_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_connectionId_t_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_qosParameter_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_qosParameter_t_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_Flow_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_Flow_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034protofiles/FlowMessage.proto\022\rrina.mes" +
      "sages\0324protofiles/ApplicationProcessNami" +
      "ngInfoMessage.proto\"N\n\016connectionId_t\022\r\n" +
      "\005qosId\030\001 \001(\004\022\023\n\013sourceCEPId\030\002 \001(\004\022\030\n\020des" +
      "tinationCEPId\030\003 \001(\004\"?\n\016qosParameter_t\022\025\n" +
      "\rparameterName\030\001 \002(\t\022\026\n\016parameterValue\030\002" +
      " \002(\t\"\215\004\n\004Flow\022G\n\020sourceNamingInfo\030\001 \002(\0132" +
      "-.rina.messages.applicationProcessNaming" +
      "Info_t\022L\n\025destinationNamingInfo\030\002 \002(\0132-." +
      "rina.messages.applicationProcessNamingIn",
      "fo_t\022\024\n\014sourcePortId\030\003 \001(\004\022\031\n\021destinatio" +
      "nPortId\030\004 \001(\004\022\025\n\rsourceAddress\030\005 \001(\004\022\032\n\022" +
      "destinationAddress\030\006 \001(\004\0224\n\rconnectionId" +
      "s\030\007 \003(\0132\035.rina.messages.connectionId_t\022\033" +
      "\n\023currentConnectionId\030\010 \001(\r\022\r\n\005state\030\t \001" +
      "(\014\0224\n\rqosParameters\030\n \003(\0132\035.rina.message" +
      "s.qosParameter_t\022\020\n\010policies\030\013 \003(\t\022\025\n\rac" +
      "cessControl\030\014 \001(\014\022\034\n\024maxCreateFlowRetrie" +
      "s\030\r \001(\r\022\031\n\021createFlowRetries\030\016 \001(\r\022\020\n\010ho" +
      "pCount\030\017 \001(\rB(\n&rina.encoding.impl.googl",
      "eprotobuf.flow"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_messages_connectionId_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_messages_connectionId_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_connectionId_t_descriptor,
              new java.lang.String[] { "QosId", "SourceCEPId", "DestinationCEPId", },
              rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t.class,
              rina.encoding.impl.googleprotobuf.flow.FlowMessage.connectionId_t.Builder.class);
          internal_static_rina_messages_qosParameter_t_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_rina_messages_qosParameter_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_qosParameter_t_descriptor,
              new java.lang.String[] { "ParameterName", "ParameterValue", },
              rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t.class,
              rina.encoding.impl.googleprotobuf.flow.FlowMessage.qosParameter_t.Builder.class);
          internal_static_rina_messages_Flow_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_rina_messages_Flow_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_Flow_descriptor,
              new java.lang.String[] { "SourceNamingInfo", "DestinationNamingInfo", "SourcePortId", "DestinationPortId", "SourceAddress", "DestinationAddress", "ConnectionIds", "CurrentConnectionId", "State", "QosParameters", "Policies", "AccessControl", "MaxCreateFlowRetries", "CreateFlowRetries", "HopCount", },
              rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow.class,
              rina.encoding.impl.googleprotobuf.flow.FlowMessage.Flow.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
