// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofiles/AllocateRequestMessage.proto

package rina.encoding.impl.googleprotobuf.allocaterequest;

public final class AllocateRequestMessage {
  private AllocateRequestMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class AllocateRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use AllocateRequest.newBuilder() to construct.
    private AllocateRequest() {
      initFields();
    }
    private AllocateRequest(boolean noInit) {}
    
    private static final AllocateRequest defaultInstance;
    public static AllocateRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public AllocateRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.internal_static_rina_messages_AllocateRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.internal_static_rina_messages_AllocateRequest_fieldAccessorTable;
    }
    
    // optional .rina.messages.applicationProcessNamingInfo_t sourceNamingInfo = 1;
    public static final int SOURCENAMINGINFO_FIELD_NUMBER = 1;
    private boolean hasSourceNamingInfo;
    private rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t sourceNamingInfo_;
    public boolean hasSourceNamingInfo() { return hasSourceNamingInfo; }
    public rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t getSourceNamingInfo() { return sourceNamingInfo_; }
    
    // required .rina.messages.applicationProcessNamingInfo_t destinationNamingInfo = 2;
    public static final int DESTINATIONNAMINGINFO_FIELD_NUMBER = 2;
    private boolean hasDestinationNamingInfo;
    private rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t destinationNamingInfo_;
    public boolean hasDestinationNamingInfo() { return hasDestinationNamingInfo; }
    public rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t getDestinationNamingInfo() { return destinationNamingInfo_; }
    
    // optional uint64 portId = 3;
    public static final int PORTID_FIELD_NUMBER = 3;
    private boolean hasPortId;
    private long portId_ = 0L;
    public boolean hasPortId() { return hasPortId; }
    public long getPortId() { return portId_; }
    
    private void initFields() {
      sourceNamingInfo_ = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance();
      destinationNamingInfo_ = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance();
    }
    public final boolean isInitialized() {
      if (!hasDestinationNamingInfo) return false;
      if (hasSourceNamingInfo()) {
        if (!getSourceNamingInfo().isInitialized()) return false;
      }
      if (!getDestinationNamingInfo().isInitialized()) return false;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSourceNamingInfo()) {
        output.writeMessage(1, getSourceNamingInfo());
      }
      if (hasDestinationNamingInfo()) {
        output.writeMessage(2, getDestinationNamingInfo());
      }
      if (hasPortId()) {
        output.writeUInt64(3, getPortId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSourceNamingInfo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSourceNamingInfo());
      }
      if (hasDestinationNamingInfo()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getDestinationNamingInfo());
      }
      if (hasPortId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, getPortId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest result;
      
      // Construct using rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest();
        return builder;
      }
      
      protected rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest.getDescriptor();
      }
      
      public rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest getDefaultInstanceForType() {
        return rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest) {
          return mergeFrom((rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest other) {
        if (other == rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest.getDefaultInstance()) return this;
        if (other.hasSourceNamingInfo()) {
          mergeSourceNamingInfo(other.getSourceNamingInfo());
        }
        if (other.hasDestinationNamingInfo()) {
          mergeDestinationNamingInfo(other.getDestinationNamingInfo());
        }
        if (other.hasPortId()) {
          setPortId(other.getPortId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.Builder subBuilder = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.newBuilder();
              if (hasSourceNamingInfo()) {
                subBuilder.mergeFrom(getSourceNamingInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSourceNamingInfo(subBuilder.buildPartial());
              break;
            }
            case 18: {
              rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.Builder subBuilder = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.newBuilder();
              if (hasDestinationNamingInfo()) {
                subBuilder.mergeFrom(getDestinationNamingInfo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDestinationNamingInfo(subBuilder.buildPartial());
              break;
            }
            case 24: {
              setPortId(input.readUInt64());
              break;
            }
          }
        }
      }
      
      
      // optional .rina.messages.applicationProcessNamingInfo_t sourceNamingInfo = 1;
      public boolean hasSourceNamingInfo() {
        return result.hasSourceNamingInfo();
      }
      public rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t getSourceNamingInfo() {
        return result.getSourceNamingInfo();
      }
      public Builder setSourceNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSourceNamingInfo = true;
        result.sourceNamingInfo_ = value;
        return this;
      }
      public Builder setSourceNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.Builder builderForValue) {
        result.hasSourceNamingInfo = true;
        result.sourceNamingInfo_ = builderForValue.build();
        return this;
      }
      public Builder mergeSourceNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t value) {
        if (result.hasSourceNamingInfo() &&
            result.sourceNamingInfo_ != rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance()) {
          result.sourceNamingInfo_ =
            rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.newBuilder(result.sourceNamingInfo_).mergeFrom(value).buildPartial();
        } else {
          result.sourceNamingInfo_ = value;
        }
        result.hasSourceNamingInfo = true;
        return this;
      }
      public Builder clearSourceNamingInfo() {
        result.hasSourceNamingInfo = false;
        result.sourceNamingInfo_ = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance();
        return this;
      }
      
      // required .rina.messages.applicationProcessNamingInfo_t destinationNamingInfo = 2;
      public boolean hasDestinationNamingInfo() {
        return result.hasDestinationNamingInfo();
      }
      public rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t getDestinationNamingInfo() {
        return result.getDestinationNamingInfo();
      }
      public Builder setDestinationNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDestinationNamingInfo = true;
        result.destinationNamingInfo_ = value;
        return this;
      }
      public Builder setDestinationNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.Builder builderForValue) {
        result.hasDestinationNamingInfo = true;
        result.destinationNamingInfo_ = builderForValue.build();
        return this;
      }
      public Builder mergeDestinationNamingInfo(rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t value) {
        if (result.hasDestinationNamingInfo() &&
            result.destinationNamingInfo_ != rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance()) {
          result.destinationNamingInfo_ =
            rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.newBuilder(result.destinationNamingInfo_).mergeFrom(value).buildPartial();
        } else {
          result.destinationNamingInfo_ = value;
        }
        result.hasDestinationNamingInfo = true;
        return this;
      }
      public Builder clearDestinationNamingInfo() {
        result.hasDestinationNamingInfo = false;
        result.destinationNamingInfo_ = rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.applicationProcessNamingInfo_t.getDefaultInstance();
        return this;
      }
      
      // optional uint64 portId = 3;
      public boolean hasPortId() {
        return result.hasPortId();
      }
      public long getPortId() {
        return result.getPortId();
      }
      public Builder setPortId(long value) {
        result.hasPortId = true;
        result.portId_ = value;
        return this;
      }
      public Builder clearPortId() {
        result.hasPortId = false;
        result.portId_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.AllocateRequest)
    }
    
    static {
      defaultInstance = new AllocateRequest(true);
      rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.AllocateRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_AllocateRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_AllocateRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\'protofiles/AllocateRequestMessage.prot" +
      "o\022\rrina.messages\0324protofiles/Application" +
      "ProcessNamingInfoMessage.proto\"\270\001\n\017Alloc" +
      "ateRequest\022G\n\020sourceNamingInfo\030\001 \001(\0132-.r" +
      "ina.messages.applicationProcessNamingInf" +
      "o_t\022L\n\025destinationNamingInfo\030\002 \002(\0132-.rin" +
      "a.messages.applicationProcessNamingInfo_" +
      "t\022\016\n\006portId\030\003 \001(\004B3\n1rina.encoding.impl." +
      "googleprotobuf.allocaterequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_messages_AllocateRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_messages_AllocateRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_AllocateRequest_descriptor,
              new java.lang.String[] { "SourceNamingInfo", "DestinationNamingInfo", "PortId", },
              rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest.class,
              rina.encoding.impl.googleprotobuf.allocaterequest.AllocateRequestMessage.AllocateRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          rina.encoding.impl.googleprotobuf.apnaminginfo.ApplicationProcessNamingInfoMessage.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
