// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protofiles/DataTransferConstantsMessage.proto

package rina.utils.serialization.googleprotobuf.datatransferconstants;

public final class DataTransferConstantsMessage {
  private DataTransferConstantsMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class dataTransferConstants_t extends
      com.google.protobuf.GeneratedMessage {
    // Use dataTransferConstants_t.newBuilder() to construct.
    private dataTransferConstants_t() {
      initFields();
    }
    private dataTransferConstants_t(boolean noInit) {}
    
    private static final dataTransferConstants_t defaultInstance;
    public static dataTransferConstants_t getDefaultInstance() {
      return defaultInstance;
    }
    
    public dataTransferConstants_t getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.internal_static_rina_messages_dataTransferConstants_t_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.internal_static_rina_messages_dataTransferConstants_t_fieldAccessorTable;
    }
    
    // optional uint32 maxPDUSize = 1;
    public static final int MAXPDUSIZE_FIELD_NUMBER = 1;
    private boolean hasMaxPDUSize;
    private int maxPDUSize_ = 0;
    public boolean hasMaxPDUSize() { return hasMaxPDUSize; }
    public int getMaxPDUSize() { return maxPDUSize_; }
    
    // optional uint32 addressLength = 2;
    public static final int ADDRESSLENGTH_FIELD_NUMBER = 2;
    private boolean hasAddressLength;
    private int addressLength_ = 0;
    public boolean hasAddressLength() { return hasAddressLength; }
    public int getAddressLength() { return addressLength_; }
    
    // optional uint32 portIdLength = 3;
    public static final int PORTIDLENGTH_FIELD_NUMBER = 3;
    private boolean hasPortIdLength;
    private int portIdLength_ = 0;
    public boolean hasPortIdLength() { return hasPortIdLength; }
    public int getPortIdLength() { return portIdLength_; }
    
    // optional uint32 qosidLength = 4;
    public static final int QOSIDLENGTH_FIELD_NUMBER = 4;
    private boolean hasQosidLength;
    private int qosidLength_ = 0;
    public boolean hasQosidLength() { return hasQosidLength; }
    public int getQosidLength() { return qosidLength_; }
    
    // optional uint32 sequenceNumberLength = 5;
    public static final int SEQUENCENUMBERLENGTH_FIELD_NUMBER = 5;
    private boolean hasSequenceNumberLength;
    private int sequenceNumberLength_ = 0;
    public boolean hasSequenceNumberLength() { return hasSequenceNumberLength; }
    public int getSequenceNumberLength() { return sequenceNumberLength_; }
    
    // optional uint32 lengthLength = 6;
    public static final int LENGTHLENGTH_FIELD_NUMBER = 6;
    private boolean hasLengthLength;
    private int lengthLength_ = 0;
    public boolean hasLengthLength() { return hasLengthLength; }
    public int getLengthLength() { return lengthLength_; }
    
    // optional uint64 seqRolloverThreshold = 7;
    public static final int SEQROLLOVERTHRESHOLD_FIELD_NUMBER = 7;
    private boolean hasSeqRolloverThreshold;
    private long seqRolloverThreshold_ = 0L;
    public boolean hasSeqRolloverThreshold() { return hasSeqRolloverThreshold; }
    public long getSeqRolloverThreshold() { return seqRolloverThreshold_; }
    
    // optional uint32 maxPDULifetime = 8;
    public static final int MAXPDULIFETIME_FIELD_NUMBER = 8;
    private boolean hasMaxPDULifetime;
    private int maxPDULifetime_ = 0;
    public boolean hasMaxPDULifetime() { return hasMaxPDULifetime; }
    public int getMaxPDULifetime() { return maxPDULifetime_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasMaxPDUSize()) {
        output.writeUInt32(1, getMaxPDUSize());
      }
      if (hasAddressLength()) {
        output.writeUInt32(2, getAddressLength());
      }
      if (hasPortIdLength()) {
        output.writeUInt32(3, getPortIdLength());
      }
      if (hasQosidLength()) {
        output.writeUInt32(4, getQosidLength());
      }
      if (hasSequenceNumberLength()) {
        output.writeUInt32(5, getSequenceNumberLength());
      }
      if (hasLengthLength()) {
        output.writeUInt32(6, getLengthLength());
      }
      if (hasSeqRolloverThreshold()) {
        output.writeUInt64(7, getSeqRolloverThreshold());
      }
      if (hasMaxPDULifetime()) {
        output.writeUInt32(8, getMaxPDULifetime());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasMaxPDUSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, getMaxPDUSize());
      }
      if (hasAddressLength()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, getAddressLength());
      }
      if (hasPortIdLength()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, getPortIdLength());
      }
      if (hasQosidLength()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, getQosidLength());
      }
      if (hasSequenceNumberLength()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, getSequenceNumberLength());
      }
      if (hasLengthLength()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, getLengthLength());
      }
      if (hasSeqRolloverThreshold()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(7, getSeqRolloverThreshold());
      }
      if (hasMaxPDULifetime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(8, getMaxPDULifetime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t result;
      
      // Construct using rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t();
        return builder;
      }
      
      protected rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t.getDescriptor();
      }
      
      public rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t getDefaultInstanceForType() {
        return rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t) {
          return mergeFrom((rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t other) {
        if (other == rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t.getDefaultInstance()) return this;
        if (other.hasMaxPDUSize()) {
          setMaxPDUSize(other.getMaxPDUSize());
        }
        if (other.hasAddressLength()) {
          setAddressLength(other.getAddressLength());
        }
        if (other.hasPortIdLength()) {
          setPortIdLength(other.getPortIdLength());
        }
        if (other.hasQosidLength()) {
          setQosidLength(other.getQosidLength());
        }
        if (other.hasSequenceNumberLength()) {
          setSequenceNumberLength(other.getSequenceNumberLength());
        }
        if (other.hasLengthLength()) {
          setLengthLength(other.getLengthLength());
        }
        if (other.hasSeqRolloverThreshold()) {
          setSeqRolloverThreshold(other.getSeqRolloverThreshold());
        }
        if (other.hasMaxPDULifetime()) {
          setMaxPDULifetime(other.getMaxPDULifetime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setMaxPDUSize(input.readUInt32());
              break;
            }
            case 16: {
              setAddressLength(input.readUInt32());
              break;
            }
            case 24: {
              setPortIdLength(input.readUInt32());
              break;
            }
            case 32: {
              setQosidLength(input.readUInt32());
              break;
            }
            case 40: {
              setSequenceNumberLength(input.readUInt32());
              break;
            }
            case 48: {
              setLengthLength(input.readUInt32());
              break;
            }
            case 56: {
              setSeqRolloverThreshold(input.readUInt64());
              break;
            }
            case 64: {
              setMaxPDULifetime(input.readUInt32());
              break;
            }
          }
        }
      }
      
      
      // optional uint32 maxPDUSize = 1;
      public boolean hasMaxPDUSize() {
        return result.hasMaxPDUSize();
      }
      public int getMaxPDUSize() {
        return result.getMaxPDUSize();
      }
      public Builder setMaxPDUSize(int value) {
        result.hasMaxPDUSize = true;
        result.maxPDUSize_ = value;
        return this;
      }
      public Builder clearMaxPDUSize() {
        result.hasMaxPDUSize = false;
        result.maxPDUSize_ = 0;
        return this;
      }
      
      // optional uint32 addressLength = 2;
      public boolean hasAddressLength() {
        return result.hasAddressLength();
      }
      public int getAddressLength() {
        return result.getAddressLength();
      }
      public Builder setAddressLength(int value) {
        result.hasAddressLength = true;
        result.addressLength_ = value;
        return this;
      }
      public Builder clearAddressLength() {
        result.hasAddressLength = false;
        result.addressLength_ = 0;
        return this;
      }
      
      // optional uint32 portIdLength = 3;
      public boolean hasPortIdLength() {
        return result.hasPortIdLength();
      }
      public int getPortIdLength() {
        return result.getPortIdLength();
      }
      public Builder setPortIdLength(int value) {
        result.hasPortIdLength = true;
        result.portIdLength_ = value;
        return this;
      }
      public Builder clearPortIdLength() {
        result.hasPortIdLength = false;
        result.portIdLength_ = 0;
        return this;
      }
      
      // optional uint32 qosidLength = 4;
      public boolean hasQosidLength() {
        return result.hasQosidLength();
      }
      public int getQosidLength() {
        return result.getQosidLength();
      }
      public Builder setQosidLength(int value) {
        result.hasQosidLength = true;
        result.qosidLength_ = value;
        return this;
      }
      public Builder clearQosidLength() {
        result.hasQosidLength = false;
        result.qosidLength_ = 0;
        return this;
      }
      
      // optional uint32 sequenceNumberLength = 5;
      public boolean hasSequenceNumberLength() {
        return result.hasSequenceNumberLength();
      }
      public int getSequenceNumberLength() {
        return result.getSequenceNumberLength();
      }
      public Builder setSequenceNumberLength(int value) {
        result.hasSequenceNumberLength = true;
        result.sequenceNumberLength_ = value;
        return this;
      }
      public Builder clearSequenceNumberLength() {
        result.hasSequenceNumberLength = false;
        result.sequenceNumberLength_ = 0;
        return this;
      }
      
      // optional uint32 lengthLength = 6;
      public boolean hasLengthLength() {
        return result.hasLengthLength();
      }
      public int getLengthLength() {
        return result.getLengthLength();
      }
      public Builder setLengthLength(int value) {
        result.hasLengthLength = true;
        result.lengthLength_ = value;
        return this;
      }
      public Builder clearLengthLength() {
        result.hasLengthLength = false;
        result.lengthLength_ = 0;
        return this;
      }
      
      // optional uint64 seqRolloverThreshold = 7;
      public boolean hasSeqRolloverThreshold() {
        return result.hasSeqRolloverThreshold();
      }
      public long getSeqRolloverThreshold() {
        return result.getSeqRolloverThreshold();
      }
      public Builder setSeqRolloverThreshold(long value) {
        result.hasSeqRolloverThreshold = true;
        result.seqRolloverThreshold_ = value;
        return this;
      }
      public Builder clearSeqRolloverThreshold() {
        result.hasSeqRolloverThreshold = false;
        result.seqRolloverThreshold_ = 0L;
        return this;
      }
      
      // optional uint32 maxPDULifetime = 8;
      public boolean hasMaxPDULifetime() {
        return result.hasMaxPDULifetime();
      }
      public int getMaxPDULifetime() {
        return result.getMaxPDULifetime();
      }
      public Builder setMaxPDULifetime(int value) {
        result.hasMaxPDULifetime = true;
        result.maxPDULifetime_ = value;
        return this;
      }
      public Builder clearMaxPDULifetime() {
        result.hasMaxPDULifetime = false;
        result.maxPDULifetime_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:rina.messages.dataTransferConstants_t)
    }
    
    static {
      defaultInstance = new dataTransferConstants_t(true);
      rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:rina.messages.dataTransferConstants_t)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_rina_messages_dataTransferConstants_t_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_rina_messages_dataTransferConstants_t_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n-protofiles/DataTransferConstantsMessag" +
      "e.proto\022\rrina.messages\"\331\001\n\027dataTransferC" +
      "onstants_t\022\022\n\nmaxPDUSize\030\001 \001(\r\022\025\n\raddres" +
      "sLength\030\002 \001(\r\022\024\n\014portIdLength\030\003 \001(\r\022\023\n\013q" +
      "osidLength\030\004 \001(\r\022\034\n\024sequenceNumberLength" +
      "\030\005 \001(\r\022\024\n\014lengthLength\030\006 \001(\r\022\034\n\024seqRollo" +
      "verThreshold\030\007 \001(\004\022\026\n\016maxPDULifetime\030\010 \001" +
      "(\rB?\n=rina.utils.serialization.googlepro" +
      "tobuf.datatransferconstants"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_rina_messages_dataTransferConstants_t_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_rina_messages_dataTransferConstants_t_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_rina_messages_dataTransferConstants_t_descriptor,
              new java.lang.String[] { "MaxPDUSize", "AddressLength", "PortIdLength", "QosidLength", "SequenceNumberLength", "LengthLength", "SeqRolloverThreshold", "MaxPDULifetime", },
              rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t.class,
              rina.utils.serialization.googleprotobuf.datatransferconstants.DataTransferConstantsMessage.dataTransferConstants_t.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
